"""
Populate the NEW template from markdown resume generated by resume-tailoring skill

This script is designed for the NEW template structure which:
- Is pre-filled with Ishupal's content (not blank placeholders)
- Uses paragraphs for responsibilities, bullets for achievements
- Has personal "Career Profile" section
- Has "Areas of Expertise" section with 3 detailed paragraphs
- Has "Career Summary" listing all jobs
- Has detailed "Work Experience" section with varying levels of detail

Usage:
    python populate_new_template.py "path/to/resume.md"
"""
from docx import Document
import shutil
import sys
import re


def parse_markdown_resume_new_format(md_file_path):
    """Parse markdown resume with new format expectations"""
    with open(md_file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    resume_data = {}

    # Extract name (first # line)
    name_match = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
    resume_data['name'] = name_match.group(1).strip().upper() if name_match else "YOUR NAME"

    # Extract title (second ## line)
    title_match = re.search(r'^##\s+(.+)$', content, re.MULTILINE)
    resume_data['title'] = title_match.group(1).strip().upper() if title_match else "JOB TITLE"

    # Extract contact info line (email | phone | location | linkedin)
    contact_line_match = re.search(r'([\w\.-]+@[\w\.-]+)\s*\|\s*(\d[\d\s]+)\s*\|\s*(.+?)\s*\|\s*(https?://[\S]+)', content)
    if contact_line_match:
        resume_data['email'] = contact_line_match.group(1).strip()
        resume_data['phone'] = contact_line_match.group(2).strip()
        resume_data['location'] = contact_line_match.group(3).strip()
        resume_data['linkedin'] = contact_line_match.group(4).strip()
    else:
        # Try simpler pattern
        email_match = re.search(r'([\w\.-]+@[\w\.-]+)', content)
        phone_match = re.search(r'(\d{4}[\s\d]{6,})', content)
        linkedin_match = re.search(r'(https?://(?:www\.)?linkedin\.com/in/[\w-]+)', content)

        resume_data['email'] = email_match.group(1) if email_match else "email@example.com"
        resume_data['phone'] = phone_match.group(1) if phone_match else "0400 000 000"
        resume_data['location'] = "Location, State"
        resume_data['linkedin'] = linkedin_match.group(1) if linkedin_match else "https://linkedin.com/in/username"

    # Extract Career Profile (section after ## CAREER PROFILE)
    career_profile_match = re.search(r'##\s+CAREER PROFILE\s*\n+(.+?)(?=\n---|\n##)', content, re.DOTALL)
    resume_data['career_profile'] = career_profile_match.group(1).strip() if career_profile_match else ""

    # Extract Areas of Expertise (3 areas with bold titles and paragraphs)
    expertise_section = re.search(r'##\s+AREAS OF EXPERTISE\s*\n+(.+?)(?=\n---|\n##)', content, re.DOTALL)
    if expertise_section:
        expertise_text = expertise_section.group(1)
        # Find all **Title:** paragraph patterns
        expertise_items = re.findall(r'\*\*([^*]+?):\*\*\s*(.+?)(?=\n\*\*|\n---|\n##|$)', expertise_text, re.DOTALL)
        resume_data['expertise'] = []
        for title, desc in expertise_items[:3]:  # Max 3
            resume_data['expertise'].append({
                'title': title.strip(),
                'description': desc.strip()
            })
    else:
        resume_data['expertise'] = []

    # Extract Career Summary (list of jobs with dates, no descriptions)
    career_summary_match = re.search(r'##\s+CAREER SUMMARY\s*\n+(.+?)(?=\n---|\n##)', content, re.DOTALL)
    resume_data['career_summary'] = []
    if career_summary_match:
        summary_text = career_summary_match.group(1)
        # Each line has: Title, Department, Company {spaces} Dates
        for line in summary_text.split('\n'):
            line = line.strip()
            if not line:
                continue
            # Split by multiple spaces (where dates are)
            parts = re.split(r'\s{2,}', line)
            if len(parts) >= 2:
                title_company = parts[0].strip()
                dates = parts[-1].strip()
                resume_data['career_summary'].append({
                    'title_company': title_company,
                    'dates': dates
                })

    # Extract Work Experience sections
    # Pattern: ### Title {spaces} Dates
    #          **Company | Location**
    #          Paragraphs...
    #          **Achievements** (optional)
    #          - bullets

    exp_pattern = r'###\s+(.+?)\s{2,}(.+?)\n\*\*(.+?)\*\*\s*\n+(.+?)(?=\n###|\n---|\n##|$)'
    experiences = re.findall(exp_pattern, content, re.DOTALL)

    resume_data['experiences'] = []
    for exp in experiences:
        title = exp[0].strip()
        dates = exp[1].strip()
        company_location = exp[2].strip()
        body = exp[3].strip()

        # Split company and location
        if '|' in company_location:
            company, location = company_location.split('|', 1)
            company = company.strip()
            location = location.strip()
        else:
            company = company_location
            location = ""

        # Separate paragraphs (responsibilities) from achievements
        achievements_match = re.search(r'\*\*Achievements?\*\*\s*\n+(.+)', body, re.DOTALL | re.IGNORECASE)

        if achievements_match:
            # Everything before **Achievements** is paragraphs
            paragraphs_text = body[:achievements_match.start()].strip()
            achievements_text = achievements_match.group(1).strip()

            # Split paragraphs (separated by blank lines)
            paragraphs = [p.strip() for p in paragraphs_text.split('\n\n') if p.strip()]

            # Extract achievement bullets
            achievements = [line.strip('- ').strip() for line in achievements_text.split('\n') if line.strip().startswith('-')]
        else:
            # No achievements section, all is paragraphs
            paragraphs = [p.strip() for p in body.split('\n\n') if p.strip()]
            achievements = []

        resume_data['experiences'].append({
            'title': title,
            'dates': dates,
            'company': company,
            'location': location,
            'paragraphs': paragraphs,
            'achievements': achievements
        })

    # Extract Education
    edu_section = re.search(r'##\s+Education\s*\n+(.+?)(?=\n---|\n##|$)', content, re.DOTALL)
    resume_data['education'] = []
    if edu_section:
        edu_text = edu_section.group(1)
        # Pattern: **University**  -   Dates
        #          Degree Specialization
        edu_items = re.findall(r'\*\*([^*]+?)\*\*\s*-\s*(.+?)\n(.+?)(?=\n\*\*|\n---|\n##|$)', edu_text, re.DOTALL)
        for uni, dates, degree in edu_items:
            resume_data['education'].append({
                'university': uni.strip(),
                'dates': dates.strip(),
                'degree': degree.strip()
            })

    # Extract Skills (categorized)
    skills_section = re.search(r'##\s+Skills\s*\n+(.+?)(?=\n---|\n##|$)', content, re.DOTALL)
    resume_data['skills'] = []
    if skills_section:
        skills_text = skills_section.group(1)
        # Pattern: **Category**
        #          skill1, skill2, skill3
        skill_categories = re.findall(r'\*\*([^*]+?)\*\*\s*\n(.+?)(?=\n\*\*|\n---|\n##|$)', skills_text, re.DOTALL)
        for category, skills in skill_categories:
            resume_data['skills'].append({
                'category': category.strip(),
                'skills': skills.strip()
            })

    return resume_data


def replace_paragraph_text(paragraph, new_text):
    """Replace entire paragraph text while preserving formatting"""
    # Clear all runs
    for run in paragraph.runs:
        run.text = ""

    # Add new text to first run
    if paragraph.runs:
        paragraph.runs[0].text = new_text
    else:
        paragraph.add_run(new_text)


def populate_new_template(resume_data, output_path):
    """Populate the NEW template with parsed resume data"""

    template_path = "resumes/Template/Template.docx"

    # Copy template
    shutil.copy(template_path, output_path)

    # Open the copy
    doc = Document(output_path)

    print(f"\nPopulating NEW template...")
    print(f"Total paragraphs in template: {len(doc.paragraphs)}")

    # Map line numbers from analysis to content
    # Line 0: NAME
    if len(doc.paragraphs) > 0:
        replace_paragraph_text(doc.paragraphs[0], resume_data['name'])

    # Line 1: TITLE
    if len(doc.paragraphs) > 1:
        replace_paragraph_text(doc.paragraphs[1], resume_data['title'])

    # Line 2: Contact info
    if len(doc.paragraphs) > 2:
        contact_line = f"{resume_data['email']}  |   {resume_data['phone']}   |  {resume_data['location']}   |   {resume_data['linkedin']}"
        replace_paragraph_text(doc.paragraphs[2], contact_line)

    # Line 7: Career Profile
    if len(doc.paragraphs) > 7 and resume_data['career_profile']:
        replace_paragraph_text(doc.paragraphs[7], resume_data['career_profile'])

    # Lines 11-13: Areas of Expertise
    for i, expertise in enumerate(resume_data['expertise'][:3]):
        para_idx = 11 + i
        if para_idx < len(doc.paragraphs):
            text = f"{expertise['title']}: {expertise['description']}"
            replace_paragraph_text(doc.paragraphs[para_idx], text)

    # Lines 16-21: Career Summary (list of all jobs)
    if resume_data['career_summary']:
        for i, job in enumerate(resume_data['career_summary'][:7]):  # Up to 7 jobs
            para_idx = 16 + i
            if para_idx < len(doc.paragraphs):
                # Format: Title, Department, Company {spaces} Dates
                line = f"{job['title_company']}                                                                   {job['dates']}"
                replace_paragraph_text(doc.paragraphs[para_idx], line)

    # Work Experience section starts at line 29
    # This is complex - need to map each experience to the right paragraphs
    # For now, let's handle the first 3 roles

    current_line = 29

    for exp_idx, exp in enumerate(resume_data['experiences'][:7]):  # Up to 7 roles
        # Title and dates line
        if current_line < len(doc.paragraphs):
            title_line = f"{exp['title']}                                                                   {exp['dates']}"
            replace_paragraph_text(doc.paragraphs[current_line], title_line)
            current_line += 1

        # Company | Location line
        if current_line < len(doc.paragraphs):
            company_line = f"{exp['company']} | {exp['location']}"
            replace_paragraph_text(doc.paragraphs[current_line], company_line)
            current_line += 1

        # Responsibility paragraphs
        for para in exp['paragraphs']:
            if current_line < len(doc.paragraphs):
                replace_paragraph_text(doc.paragraphs[current_line], para)
                current_line += 1

        # Achievements heading (if there are achievements)
        if exp['achievements']:
            if current_line < len(doc.paragraphs):
                replace_paragraph_text(doc.paragraphs[current_line], "Achievements")
                current_line += 1

            # Achievement bullets
            for ach in exp['achievements']:
                if current_line < len(doc.paragraphs):
                    replace_paragraph_text(doc.paragraphs[current_line], ach)
                    current_line += 1

        # Skip blank line
        current_line += 1

    # Education section (around line 95-99)
    edu_start = 95
    for i, edu in enumerate(resume_data['education'][:2]):
        # University and dates line
        idx1 = edu_start + (i * 3)
        idx2 = idx1 + 1
        if idx1 < len(doc.paragraphs):
            uni_line = f"{edu['university']}  -   {edu['dates']}"
            replace_paragraph_text(doc.paragraphs[idx1], uni_line)
        if idx2 < len(doc.paragraphs):
            replace_paragraph_text(doc.paragraphs[idx2], edu['degree'])

    # Skills section (around line 102-107)
    skills_start = 102
    for i, skill_cat in enumerate(resume_data['skills'][:6]):
        idx = skills_start + i
        if idx < len(doc.paragraphs):
            # Format: **Category**\n skills, list
            text = f"{skill_cat['category']}\n{skill_cat['skills']}"
            replace_paragraph_text(doc.paragraphs[idx], text)

    # Save
    doc.save(output_path)
    print(f"\nResume saved to: {output_path}")
    return output_path


def find_latest_md_file():
    """Find the most recently modified resume .md file in resumes folder"""
    import os
    import glob

    # Look for .md files in resumes folder
    md_files = glob.glob("resumes/*.md")

    # Filter to only include files with "Resume" in the name (not Cover Letter, etc.)
    resume_files = [f for f in md_files if "Resume" in f or "resume" in f]

    if not resume_files:
        # If no files with "Resume" in name, fall back to all .md files
        resume_files = md_files

    if not resume_files:
        return None

    # Sort by modification time, most recent first
    resume_files.sort(key=os.path.getmtime, reverse=True)

    return resume_files[0]


def main():
    # If user provided a file path, use it
    if len(sys.argv) >= 2:
        md_file = sys.argv[1]
        print(f"Using specified file: {md_file}")
    else:
        # Otherwise, find the most recent .md file automatically
        md_file = find_latest_md_file()

        if not md_file:
            print("ERROR: No .md files found in resumes/ folder")
            print("\nPlease either:")
            print("  1. Place your resume .md file in the resumes/ folder")
            print("  2. Specify the path: python populate_new_template.py <path_to_resume.md>")
            return

        print(f"No file specified. Using most recent .md file: {md_file}")

    print(f"Reading markdown resume: {md_file}")
    resume_data = parse_markdown_resume_new_format(md_file)

    print(f"\nParsed resume data:")
    print(f"  Name: {resume_data['name']}")
    print(f"  Title: {resume_data['title']}")
    print(f"  Email: {resume_data['email']}")
    print(f"  Career Profile: {len(resume_data['career_profile'])} chars")
    print(f"  Areas of Expertise: {len(resume_data['expertise'])} areas")
    print(f"  Career Summary: {len(resume_data['career_summary'])} jobs")
    print(f"  Detailed Experiences: {len(resume_data['experiences'])} roles")
    print(f"  Education: {len(resume_data['education'])} degrees")
    print(f"  Skill Categories: {len(resume_data['skills'])} categories")

    # Generate output filename
    base_name = md_file.replace('.md', '').split('/')[-1].split('\\')[-1]
    output_path = f"resumes/{base_name} - NEW TEMPLATE.docx"

    print(f"\nPopulating NEW template...")
    populate_new_template(resume_data, output_path)

    print(f"\n✓ Complete! Your resume is ready.")
    print(f"\nWorkflow completed:")
    print(f"  1. ✓ Skill generated: {md_file}")
    print(f"  2. ✓ Parsed markdown content")
    print(f"  3. ✓ Populated NEW template: {output_path}")


if __name__ == "__main__":
    main()
